### ISSUE TITLE
provide es5 builds

### ISSUE THREAD

**Issue by zaaack** [expert-elm/util-extra#16]
Currently, util-extra is targeting es2017 (or es2018?), the dist files contains some syntax like async/await are not supported by many browsers.

**Comment by HairyRabbit** [comment]
I write a tool to resolve this problem, the new packer will package all kinds of module type bundle and works with different platforms.

**Comment by HairyRabbit** [comment]
The PR come soon

**Comment by HairyRabbit** [comment]
@zaaack new version **v0.0.15** released and switch to **ES5** target. would you have any idea about how to struct dist folder?

in my case:

1. the origin directory _**dist/**_ apply to tsc's es5 target, and generate .js, .js.map, .d.ts, .d.ts.map each file.
2. _**dist/module**_ will generate .mjs files for the nodejs es module system, also include .mjs, .mjs.map, .d.ts and .d.ts.map
3. _**dist/browser-module**_ also generate mjs files but for browser native module system like `<script type="module">`, include .mjs, .mjs.map. looks like the no need to generate type declaration files.
4. _**dist/deno**_, this folder for deno use case, and will copy from source files to here, and append .ts extension for each import declaration.
5. _**dist/umd**_, for umd bundle, you may not need this.

**Comment by zaaack** [comment]
@HairyRabbit Looks good to me.

**Comment by HairyRabbit** [comment]
ts-repack works well, and joined build toolchain
